name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build homebridge-boschclimateseries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run build

